# Generated by Django 6.0 on 2026-01-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0007_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='created_at',
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
