# Generated by Django 5.2.8 on 2026-01-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0011_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('furniture', 'Furniture'), ('wall_decor', 'Wall Decor'), ('kitchen', 'Kitchen & Dining'), ('lighting', 'Lighting'), ('bath', 'Bath Decor')], default='home', max_length=50),
            preserve_default=False,
        ),
    ]
