# Generated by Django 5.2.8 on 2026-01-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0014_alter_banner_page_alter_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('furniture', 'Furniture'), ('lighting', 'Lighting'), ('bath', 'Accessories')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
