# Generated by Django 5.2.8 on 2026-01-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0015_alter_banner_page_alter_product_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='is_active',
        ),
    ]
