# Generated by Django 5.2.8 on 2026-01-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0017_banner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
