# Generated by Django 5.2.8 on 2026-01-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0018_alter_subcategory_name_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='created_at',
        ),
    ]
