# Generated by Django 6.0 on 2026-02-13 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0035_order_coupon_code_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
