# Generated by Django 6.0 on 2026-03-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0038_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('furniture', 'Furniture'), ('walldecor', 'Wall Decor'), ('kitchen', 'Kitchen'), ('lighting', 'Lighting'), ('bath', 'Accessories')], max_length=50),
        ),
    ]
