# Generated by Django 6.0 on 2026-03-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0039_alter_banner_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
