# Generated by Django 6.0 on 2026-03-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloom', '0041_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/'),
        ),
    ]
