from django.urls import path
from bloom import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('',views.home,name='home'),
    path('furniture',views.furniture,name='furniture'),
    path('walldecor',views.walldecor,name='walldecor'),
    path('kitchen/',views.kitchen,name='kitchen'),
    path('lighting',views.lighting,name='lighting'),
    path('bath',views.bath,name='bath'),
    path('login/',views.login_view,name='login'),
    path('signup',views.signup_view,name='signup'),
    path('forgot',views.forgot,name='forgot'),
    path("verify-otp/", views.verify_otp, name="verify_otp"),
    path("reset-password/", views.reset_password, name="reset_password"),
    path("password-changed/", views.password_changed, name="password_changed"),
    path('profile/',views.profile,name='profile'),
    path("profile/edit/", views.editprofile, name="edit_profile"),
    path('order',views.order,name='order'),
    path("order-success/", views.ordersuccess, name="ordersuccess"),
    path("admin/order/<int:order_id>/status/",views.update_order_status,name="update_order_status"),
    path("detail/<int:id>/", views.detail, name="detail"),
    path("invoice/<int:id>/",views.download_invoice,name="download_invoice"),
    path('adminorder',views.adminorder,name='adminorder'),
    path("orders/<int:order_id>/status/",views.update_order_status, name="update_order_status"),
    path('address/add/', views.addaddress, name='addaddress'),
    path("address/delete/<int:id>/", views.delete_address, name="delete_address"),
    path("address/edit/<int:id>/", views.editaddress, name="edit_address"),
    path('wishlist',views.wishlist,name='wishlist'),
    path('wishlist/toggle/<int:product_id>/', views.toggle_wishlist, name='toggle_wishlist'),
    path('wishlist/move-to-cart/<int:wishlist_id>/', views.move_to_cart, name='move_to_cart'),
    path("cart/", views.cart, name="cart"),
    path("cart/remove/<int:item_id>/", views.remove_cart_item, name="remove_cart_item"),
    path('checkout',views.checkout,name='checkout'),
    path('faq',views.faq,name='faq'),
    path('parivacy',views.privacy,name='privacy'),
    path('aboutus',views.aboutus,name='aboutus'),
    path("product/<int:pk>/", views.product, name="product"),
    path('admindashboard/',views.admindashboard,name='admindashboard'),
    path('adminproduct/',views.adminproduct,name='adminproduct'),
    path("productedit/<int:pk>/", views.productedit, name="productedit"),
    path('product/toggle/<int:id>/', views.product_toggle_status, name='product_toggle'),
    path('admincutomer/',views.admincustomer,name='admincustomer'),
    path("dashboard/customers/delete/<int:user_id>/", views.delete_customer, name="delete_customer"),  
    path("customer/block/<int:user_id>/", views.toggle_customer_block, name="toggle_customer_block"), 
    path('admincategory',views.admincategory,name='admincategory'),
    path("categoryedit/<int:pk>/", views.categoryedit, name="categoryedit"),
    path("categoryadd/", views.categoryadd, name="categoryadd"),
    path('admincoupon/',views.admincoupon,name='admincoupon'),
    path('couponedit/',views.couponedit,name='couponedit'),
    path("add_product/", views.add_product, name="addproduct"),
    path("categorydelete/<int:pk>/", views.categorydelete, name="categorydelete"),
    path("logout/", views.userlogout, name="userlogout"),
    path("adminlogout/", views.adminlogout, name="adminlogout"),
    path("adminbanner/", views.banner_add, name="banner_add"),
    path("product/<int:id>/", views.product_detail, name="product_detail"),
    path("search/", views.search, name="search"),
    path("pay/",views.payment_page, name="payment_page"),
    path("place-order/",views.place_order, name="place_order"),
    path("payment-success/", views.payment_success, name="payment_success"),
    path("payment-failed/",views.payment_failed,name='payment_failed'),

    





]